name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upstream Pull Request
      env:
        UPSTREAM: https://github.com/j-hc/revanced-magisk-module
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        
        git remote add upstream "${UPSTREAM}"
        
        # Verify upstream is correct, you should see the URL for the upstream fetch and push 
        git remote -v
        
        # Get all recent branches and commits from the upstream
        git fetch upstream
        
        git pull upstream main
        
        #change branch
        git checkout -b upstream
        
        # Merge the branches and commits from the upstream
        git merge upstream/main --ff-only
        
        git add . --force
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Merge upstream ${{ steps.date.outputs.date }}
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: upstream
        delete-branch: true
        title: 'Merge Upstream'
        body: |
          Update upstream
          - Updated with *today's* date
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash

        
