name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          head: j-hc/revanced-magisk-module
          base: main
            
#     - name: Enable Pull Request Automerge
#       uses: peter-evans/enable-pull-request-automerge@v2
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
#         merge-method: squash

        
