name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

        
