name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upstream Pull Request
      env:
        UPSTREAM: https://github.com/j-hc/revanced-magisk-module
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        
        git remote add upstream "${UPSTREAM}"
        
        # Verify upstream is correct, you should see the URL for the upstream fetch and push 
        git remote -v
        
        # Get all recent branches and commits from the upstream
        git fetch upstream
        
        git pull upstream main
        
        gh pr create --title "Merge Upstream" --body "Update from upstream repo" --base main --head upstream:main
        
#     - name: Enable Pull Request Automerge
#       uses: peter-evans/enable-pull-request-automerge@v2
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
#         merge-method: squash

        
